name: Update Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}
    
    - name: Execute PowerShell Script
      id: get-data  # Important: this ID is used to reference the output
      shell: pwsh
      run: ./script.ps1 -Instance ${{ secrets.DB_HOST }} -DbName ${{ secrets.DB_DATABASE }} -UID ${{ secrets.DB_USER }} -Password ${{ secrets.DB_PASSWORD }}

    - name: Debug output
      run: |
        echo "Received data: ${{ steps.get-data.outputs.data }}"
          
    - name: Update file with JSON data
      run: |
        echo ${{ steps.get-data.outputs.data }} > data/statistics.min.json
        jq . data/statistics.min.json > temp.json && mv temp.json data/statistics.min.json
        
    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code data/statistics.min.json || echo "changes=true" >> $GITHUB_OUTPUT
          
    - name: Commit and push changes
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add data/statistics.min.json
        git commit -m "Update file with new JSON data"
        git push
