name: Update Data

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Execute PowerShell Script
      run: |
        ./script.ps1 -Instance ${{ secrets.DB_INSTANCE }} -DB_HOST ${{ secrets.DB_DATABASE }} -UID ${{ secrets.DB_USER }} -Password ${{ secrets.DB_PASSWORD }}
